### ISSUE TITLE
Move all code to the python's packages

### ISSUE THREAD

**Issue by extsoft** [qaivanpleten/sp_learning#1]
Main package - `sp_at`. All other packages have to be located within `sp_at`.

**Comment by qaivanpleten** [comment]
@extsoft 
а что означает это _at в конце названия корневой папки? я заметил, что и в твоем проекте так папк называется, и на repspark мы так делали

**Comment by extsoft** [comment]
Done

**Comment by extsoft** [comment]
`_at`  = automated tests
