### ISSUE TITLE
вопрос по хранению переменных

### ISSUE THREAD

**Issue by qaivanpleten** [qaivanpleten/sp_learning#6]
@extsoft 
у меня тут возник такой интересный вопрос по поводу того как я хряню и переиспользую переменные. конкретно элементы на страницах. что я имею в виду. 
вот у меня есть для каждой страницы файл `bla_bla_elements.py`
в каждом из таких файлов куча функций, каждая из которых возвращает `self.driver.find_element_by_xpath("bla bla bla")`
Когда я хочу что то сделать с элементом в тесте, я вызываю нужную функцию. 

вопрос. могу ли я хранить в `bla_bla_elements.py` одну функцию, которая не будет ничего возвращать, но будет хранить кучу переменных, с которыми я буду работать? 
то есть, будет что то типа

```
class EditUserPageElements:
    def __init__(self, driver):
        self.driver = driver

    def elements(self):
       a = self.driver.find_element_by_id('username')
       b = self.driver.find_element_by_xpath('//*[@id="username"]/div/input')
```

И потом когда я захочу например кликнуть по элементу `а` в тесте я напишу что то типа
`EditUserPageElement(self.drive).elements().a.click()`

Я сделал так, как у меня сделано потому, что мне так сказал более опытный чувак-девелопер. Я тогда мало знал и просто сделал. А теперь подумал, оставить все как есть или просто хранить кучу переменых?

**Comment by extsoft** [comment]
First of all, read these two articles:
- https://martinfowler.com/bliki/PageObject.html
- https://github.com/SeleniumHQ/selenium/wiki/PageObjects

Next one. If you need to use elements in the tests, you can do next:
```python
class EditUserPageElements:
    def __init__(self, driver):
        self.driver = driver

   def usename(self):
      """Allows to interact with 'username' field"""
       return elf.driver.find_element_by_id('username')

   def edit_username(self, new_username):
       """Allows to set new user name"""
       self.username().send_keys(new_username)
```

Method `usename()` returns a `WebElement` of a username field. So, you can interact with it directly. 

Method `edit_username()` uses `usename()` and does some interaction with a page.

And I would recommend keeping these methods in the separate classes as each of them has it own purpose:
- `usename()` - access to page element
- `edit_username()` - small action on a page (page object method)

**Comment by qaivanpleten** [comment]
@extsoft 
got it. thanks
