### ISSUE TITLE
How to check that value in Select is selected? 

### ISSUE THREAD

**Issue by qaivanpleten** [qaivanpleten/sp_learning#7]
@extsoft  
Do you happen to know how to check value in standard HTML select?
E.g. here is my select: 
```
<select class="sp-select-role" disabled="disabled">
     <option value="0">admin</option>
     <option value="1">member</option>
</select>
```
I want to check that `value="0"` is selected. How can I do it ?

**Comment by extsoft** [comment]
@qaivanpleten 
Please take a look for [this example](https://github.com/tourdedave/elemental-selenium-tips/blob/master/05-select-from-a-dropdown/python/dropdown.py). `test_example_2` is the best one.

**Comment by qaivanpleten** [comment]
got it. thanks
