### ISSUE TITLE
discuss how to run folder with tests, using py.test

### ISSUE THREAD

**Issue by qaivanpleten** [qaivanpleten/sp_learning#9]
@extsoft 
I was trying this way: 
![image](https://user-images.githubusercontent.com/22939073/30644812-53fa6ecc-9e1c-11e7-8f39-3c80159101fb.png)

And this one: 
![image](https://user-images.githubusercontent.com/22939073/30644839-6d1ad87e-9e1c-11e7-8c15-0311fbf29fee.png)

Results were the same. `collected 0 items `

**Comment by extsoft** [comment]
@qaivanpleten Please take a look through https://pytest.readthedocs.io/en/reorganize-docs/new-docs/user/naming_conventions.html.

**Comment by qaivanpleten** [comment]
@extsoft 
got it. thanks
